[package]
name = "fast_circles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou="0.17"
random="0.13.2"
grid="0.9.0"
